name: Auto Deploy to CPanel Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to cPanel using FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /public_html/dclass/       # phải kết thúc bằng dấu /
          exclude: |
            .github/
            .gitignore
            README.md
            deploy.yml
            **/.git*
            **/node_modules*
